SELECT TO_CHAR(DATE_TRUNC('month', "DATA"), 'YYYY-MM') AS MES,
    SUM("VALORLIQUIDOVENDA") as VENDA
FROM vendas
WHERE "IDVENDEDOR" = :IDVENDEDOR
    AND "DATA" >= DATE_TRUNC('month', CURRENT_DATE - INTERVAL '15 months')
GROUP BY MES
ORDER BY MES