SELECT O.IDORCAMENTO,
        O.ENDERECO || ',' || O.NUMERO || ' - COMPL.: ' || O.COMPLEMENTO || ' - BAIRRO: ' || O.BAIRRO || ' - CIDADE: ' || CI.DESCRCIDADE || '-' || O.UF AS ENDERECOCOMPLETO,
        O.IDCEP,
        O.UF,
        O.OBSERVACAO,
        O.CNPJCPF,
        O.BAIRRO,
        O.NUMERO,
        O.COMPLEMENTO,
        O.FONECELULAR,
        O.IDCLIFOR || '-' || O.NOME AS CLIENTE,
        O.NOME AS NOME,
        OP.IDVENDEDOR,
        VENDEDOR.NOME AS NOMEVENDEDOR,
        VENDEDOR.EMAIL AS EMAILVENDEDOR,
        O.IDEMPRESA,
        O.FLAGCANCELADO,
        EMPRESA.EMPALIAS AS NOMELOJA,
        EMPRESA.FONE AS FONEEMPRESA,
        EMPRESA.EMAIL AS EMAILEMPRESA,
        EMPRESA.ENDERECO || ',' || EMPRESA.NUMERO || ' - ' || EMPRESA.BAIRRO || ' - ' || CIDEMP.DESCRCIDADE AS ENDERECOEMPRESA,
        PERFIL.DESCRICAO AS PERFILFRETE,
        CAST(SUM(OP.VALTOTLIQUIDO) AS VARCHAR(20)) AS VALTOTLIQUIDO
FROM DBA.ORCAMENTO AS O
        LEFT JOIN DBA.ORCAMENTO_PROD AS OP ON O.IDORCAMENTO = OP.IDORCAMENTO
        AND O.IDEMPRESA = OP.IDEMPRESA
        LEFT JOIN DBA.CLIENTE_FORNECEDOR AS VENDEDOR ON OP.IDVENDEDOR = VENDEDOR.IDCLIFOR
        LEFT JOIN DBA.EMPRESA AS EMPRESA ON EMPRESA.IDEMPRESA = O.IDEMPRESA
        LEFT JOIN DBA.CIDADES_IBGE AS CI ON CI.IDCIDADE = O.IDCIDADE
        LEFT JOIN DBA.CIDADES_IBGE AS CIDEMP ON EMPRESA.IDCIDADE = CIDEMP.IDCIDADE
        LEFT JOIN DBA.PERFIL_FRETE AS PERFIL ON O.IDPERFIL = PERFIL.IDPERFIL
WHERE O.IDORCAMENTO = ':IDORCAMENTO'
GROUP BY O.IDORCAMENTO,
        O.ENDERECO || ',' || O.NUMERO || ' - COMPL.: ' || O.COMPLEMENTO || ' - BAIRRO: ' || O.BAIRRO || ' - CIDADE: ' || CI.DESCRCIDADE || '-' || O.UF,
        O.IDCEP,
        O.UF,
        O.OBSERVACAO,
        O.CNPJCPF,
        O.BAIRRO,
        O.NUMERO,
        O.COMPLEMENTO,
        O.FONECELULAR,
        O.IDCLIFOR || '-' || O.NOME,
        O.NOME,
        OP.IDVENDEDOR,
        VENDEDOR.NOME,
        VENDEDOR.EMAIL,
        O.IDEMPRESA,
        O.FLAGCANCELADO,
        EMPRESA.EMPALIAS,
        EMPRESA.FONE,
        EMPRESA.EMAIL,
        EMPRESA.ENDERECO || ',' || EMPRESA.NUMERO || ' - ' || EMPRESA.BAIRRO || ' - ' || CIDEMP.DESCRCIDADE,
        PERFIL.DESCRICAO