select O.idorcamento,
    OP.IDVENDEDOR,
    CAST(qtdproduto AS VARCHAR(20)) AS QTDPRODUTO,
    CAST(valunitbruto AS VARCHAR(20)) AS VALUNITBRUTO,
    CAST(valtotliquido AS VARCHAR(20)) AS VALTOTLIQUIDO,
    CAST(valfrete AS VARCHAR (20)) AS VALFRETE
from dba.orcamento_prod AS OP
    LEFT JOIN DBA.ORCAMENTO AS O ON OP.IDORCAMENTO = O.IDORCAMENTO
    AND OP.IDEMPRESA = O.IDEMPRESA
where O.FLAGPRENOTA = 'F'
    AND O.DTMOVIMENTO >= CURRENT DATE -120
    AND OP.IDPRODUTO in (:IDPRODUTO)
    and op.idvendedor in (:IDVENDEDOR)