SELECT DISTINCT 'P' AS TIPO,
    ORCAMENTO_PROD.IDEMPRESA,
    CAST(ORCAMENTO_PROD.IDORCAMENTOORIGEM AS VARCHAR(20)) AS IDORCAMENTOORIGEM,
    EMPRESA.NOMEFANTASIA,
    ORCAMENTO.IDCLIFOR,
    CLIENTE_FORNECEDOR.NOME,
    CI.DESCRCIDADE,
    CI.UF,
    --DATE(ORCAMENTO.DTMOVIMENTO) AS DATA,
    --ORCAMENTO.DTMOVIMENTO AS DATAHORA,
    ORCAMENTO_PROD.IDORCAMENTO,
    CAST(
        COALESCE(SUM(ORCAMENTO_PROD.VALTOTLIQUIDO), 0) AS VARCHAR(20)
    ) AS VALOR_VENDA,
    CAST(
        COALESCE(SUM(ORCAMENTO_PROD.VALFRETE), 0) AS VARCHAR(20)
    ) AS VALFRETE_VENDA
FROM DBA.EMPRESA AS EMPRESA
    JOIN DBA.ORCAMENTO AS ORCAMENTO ON (EMPRESA.IDEMPRESA = ORCAMENTO.IDEMPRESA)
    JOIN DBA.CLIENTE_FORNECEDOR AS CLIENTE_FORNECEDOR ON (ORCAMENTO.IDCLIFOR = CLIENTE_FORNECEDOR.IDCLIFOR)
    JOIN DBA.ORCAMENTO_PROD AS ORCAMENTO_PROD ON (
        ORCAMENTO.IDEMPRESA = ORCAMENTO_PROD.IDEMPRESA
        AND ORCAMENTO.IDORCAMENTO = ORCAMENTO_PROD.IDORCAMENTO
    )
    JOIN DBA.PRODUTOS_VIEW AS PRODUTOS_VIEW ON (
        ORCAMENTO_PROD.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
        AND ORCAMENTO_PROD.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
    )
    JOIN DBA.CIDADES_IBGE AS CI ON (CI.IDCIDADE = ORCAMENTO.IDCIDADE)
    LEFT JOIN DBA.MARCA AS MARCA ON (MARCA.DESCRICAO = PRODUTOS_VIEW.FABRICANTE)
WHERE ORCAMENTO.FLAGPRENOTAPAGA = 'T'
    AND ORCAMENTO_PROD.IDVENDEDOR in (:IDVENDEDOR)
    AND DATE(ORCAMENTO.DTMOVIMENTO) BETWEEN CURRENT DATE -120 AND CURRENT DATE --        ORCAMENTO_PROD.IDORCAMENTO IN (:RA_IDORCAMENTO) AND
    --        ORCAMENTO_PROD.IDEMPRESA IN (:RA_IDEMPRESA) AND
    AND NOT EXISTS (
        SELECT 1
        FROM DBA.CLIENTE_FORNECEDOR AS CF,
            DBA.EMPRESA AS EMP
        WHERE CF.CNPJCPF = EMP.CNPJ
            AND CF.IDCLIFOR = ORCAMENTO.IDCLIFOR
            AND EMP.IDEMPRESA IN (
                SELECT DISTINCT IDEMPRESAENTRADA
                FROM DBA.CONFIG_TRANSF_NOTA
            )
    )
GROUP BY ORCAMENTO_PROD.IDEMPRESA,
    CAST(ORCAMENTO_PROD.IDORCAMENTOORIGEM AS VARCHAR(20)),
    EMPRESA.NOMEFANTASIA,
    ORCAMENTO.IDCLIFOR,
    CLIENTE_FORNECEDOR.NOME,
    CI.DESCRCIDADE,
    CI.UF,
    --DATE(ORCAMENTO.DTMOVIMENTO) ,
    --ORCAMENTO.DTMOVIMENTO ,
    ORCAMENTO_PROD.IDORCAMENTO