SELECT TEMP.IDPRODUTO,
    sum(temp.qtdorcamento) as qtdorcamento,
    CAST(SUM(TEMP.QTDPRODUTO) AS VARCHAR(20)) AS QTDPRODUTO,
    CAST(SUM(TEMP.VALTOTLIQUIDO) AS VARCHAR(20)) AS VALTOTLIQUIDO
FROM (
        SELECT OP.IDPRODUTO,
            OP.IDVENDEDOR,
            O.IDEMPRESA,
            count(o.idorcamento) as qtdorcamento,
            SUM(OP.QTDPRODUTO) AS QTDPRODUTO,
            SUM(OP.VALTOTLIQUIDO) AS VALTOTLIQUIDO,
            (
                SELECT VDH.IDDEPARTAMENTO
                FROM DBA.VENDEDOR_DEPARTAMENTO_HIST AS VDH
                WHERE VDH.IDVENDEDOR = OP.IDVENDEDOR
                    AND VDH.DTCADASTRO = (
                        SELECT MAX(VDH.DTCADASTRO) AS DT
                        FROM DBA.VENDEDOR_DEPARTAMENTO_HIST AS VDH
                        WHERE VDH.IDVENDEDOR = OP.IDVENDEDOR
                            AND VDH.DTCADASTRO <= O.DTMOVIMENTO
                    )
            ) AS IDDEPARTAMENTO
        FROM DBA.ORCAMENTO AS O
            LEFT JOIN DBA.ORCAMENTO_PROD AS OP ON O.IDORCAMENTO = OP.IDORCAMENTO
            AND O.IDEMPRESA = OP.IDEMPRESA
        WHERE FLAGPRENOTAPAGA = 'F'
            AND FLAGPRENOTA = 'F'
            AND O.DTMOVIMENTO >= CURRENT DATE -30 --AND IDPRODUTO= 1096336
            AND OP.IDORCAMENTOORIGEM IS NULL
            AND IDPRODUTO IS NOT NULL
            AND O.FLAGCANCELADO = 'F'
        GROUP BY OP.IDPRODUTO,
            OP.IDVENDEDOR,
            O.IDEMPRESA,
            O.DTMOVIMENTO
        ORDER BY SUM(OP.VALTOTLIQUIDO) DESC
    ) AS TEMP
WHERE TEMP.IDDEPARTAMENTO = ':IDDEPARTAMENTO'
GROUP BY TEMP.IDPRODUTO
ORDER BY SUM(TEMP.VALTOTLIQUIDO) DESC
LIMIT 20