SELECT CLIENTE_FORNECEDOR.IDCLIFOR,
    CLIENTE_FORNECEDOR.NOME,
    CI.IDCLUBE,
    CF.DESCRCLUBE
FROM DBA.CLIENTE_FORNECEDOR AS CLIENTE_FORNECEDOR
    LEFT OUTER JOIN DBA.GRUPO_ECONOMICO AS GRUPO_ECONOMICO ON (
        CLIENTE_FORNECEDOR.IDGRUPOECONOMICO = GRUPO_ECONOMICO.IDGRUPOECONOMICO
    )
    LEFT JOIN DBA.CLUBE_INDICADOR AS CI ON (CLIENTE_FORNECEDOR.IDCLIFOR = CI.IDINDICADOR)
    LEFT JOIN DBA.CLUBE_FIDELIZACAO AS CF ON (CI.IDCLUBE = CF.IDCLUBE)
    LEFT JOIN DBA.CLIENTE_AUTORIZADOS AS CLIENTE_AUTORIZADOS ON (
        CLIENTE_FORNECEDOR.IDCLIFOR = CLIENTE_AUTORIZADOS.IDCLIFOR
    )
    LEFT JOIN DBA.PESSOA_FISICA AS PESSOA_FISICA ON (
        CLIENTE_FORNECEDOR.IDCLIFOR = PESSOA_FISICA.IDCLIFOR
    )
WHERE CI.IDCLUBE IS NOT NULL
    AND CI.FLAGINATIVO = 'F'
    AND (
        CLIENTE_FORNECEDOR.CNPJCPF = ':CNPJCPF'
        OR -- CLIENTE_FORNECEDOR.NOME LIKE '%:CNPJCPF%' OR
        CLIENTE_FORNECEDOR.FONE2 = ':CNPJCPF'
        OR CLIENTE_FORNECEDOR.FONE1 = ':CNPJCPF'
        OR CLIENTE_FORNECEDOR.FONEFAX = ':CNPJCPF'
        OR CLIENTE_FORNECEDOR.FONECELULAR = ':CNPJCPF'
    )