SELECT CLUBE.IDINDICADOR,
    CLUBE.NOMEINDICADOR,
    CLUBE.CNPJCPF_IND,
    CAST(count(temp.idorcamento) AS VARCHAR(10)) as qtdvendas,
    CLUBE.FONECELULAR,
    VENDEDOR.IDCLIFOR AS IDVENDEDOR,
    VENDEDOR.NOME AS NOMEVENDEDOR,
    MAX(TEMP.DATA) AS ULTIMACOMPRA,
    CAST(
        DAYS(CURRENT DATE) - DAYS(MAX(TEMP.DATA)) AS VARCHAR(10)
    ) AS DIASSEMCOMPRAS,
    (
        CASE
            WHEN (CURRENT DATE - MAX(TEMP.DATA)) BETWEEN 61 AND 90 THEN 'ATENÇÃO'
            WHEN (CURRENT DATE - MAX(TEMP.DATA)) > 91 THEN 'INATIVO'
            ELSE 'ATIVO'
        END
    ) AS STATUS,
    CAST(
        ROUND(SUM(COALESCE(TEMP.VALOR_VENDA, 0)), 2) AS VARCHAR(20)
    ) AS VALOR_VENDA_INDICADOR,
    CAST(
        ROUND(SUM(COALESCE(TEMP.VALFRETE_VENDA, 0)), 2) AS VARCHAR(20)
    ) AS VALFRETE_VENDA_INDICADOR,
    CAST(
        ROUND(
            SUM(COALESCE(TEMP.VALOR_DEV, 0)) - SUM(COALESCE(TEMP.VALFRETE_DEV, 0)),
            2
        ) AS VARCHAR(20)
    ) AS VALOR_DEV_INDICADOR,
    CAST(
        ROUND(SUM(COALESCE(TEMP.VALOR_CAN, 0)), 2) AS VARCHAR(20)
    ) AS VALOR_CAN_INDICADOR,
    CAST(
        ROUND(
            (
                (
                    SUM(COALESCE(TEMP.VALOR_VENDA, 0)) - SUM(COALESCE(TEMP.VALFRETE_VENDA, 0))
                ) - (
                    SUM(COALESCE(TEMP.VALOR_DEV, 0)) - SUM(COALESCE(TEMP.VALFRETE_DEV, 0))
                ) - (SUM(COALESCE(TEMP.VALOR_CAN, 0)))
            ),
            2
        ) AS VARCHAR(20)
    ) AS VALORLIQUIDOVENDAINDICADOR
FROM (
        SELECT DISTINCT 'P' AS TIPO,
            ORCAMENTO_PROD.IDEMPRESA,
            EMPRESA.NOMEFANTASIA,
            ORCAMENTO.IDCLIFOR,
            CLIENTE_FORNECEDOR.NOME,
            CI.DESCRCIDADE,
            CI.UF,
            DATE(ORCAMENTO.DTMOVIMENTO) AS DATA,
            ORCAMENTO_PROD.IDORCAMENTO,
            ORCAMENTO_PROD.IDVENDEDOR,
            ORCAMENTO_PROD.IDPRODUTO,
            ORCAMENTO_PROD.IDSUBPRODUTO,
            PRODUTOS_VIEW.FABRICANTE AS MARCA,
            ORCAMENTO_PROD.NUMSEQUENCIA,
            PRODUTOS_VIEW.DESCRICAOPRODUTO AS DESCRICAOPRODUTO,
            COALESCE(ORCAMENTO_PROD.VALTOTLIQUIDO, 0) AS VALOR_VENDA,
            COALESCE(ORCAMENTO_PROD.VALFRETE, 0) AS VALFRETE_VENDA,
            0 AS VALOR_DEV,
            0 AS VALFRETE_DEV,
            0 AS VALOR_CAN
        FROM DBA.EMPRESA AS EMPRESA
            JOIN DBA.ORCAMENTO AS ORCAMENTO ON (EMPRESA.IDEMPRESA = ORCAMENTO.IDEMPRESA)
            JOIN DBA.CLIENTE_FORNECEDOR AS CLIENTE_FORNECEDOR ON (ORCAMENTO.IDCLIFOR = CLIENTE_FORNECEDOR.IDCLIFOR)
            JOIN DBA.ORCAMENTO_PROD AS ORCAMENTO_PROD ON (
                ORCAMENTO.IDEMPRESA = ORCAMENTO_PROD.IDEMPRESA
                AND ORCAMENTO.IDORCAMENTO = ORCAMENTO_PROD.IDORCAMENTO
            )
            JOIN DBA.PRODUTOS_VIEW AS PRODUTOS_VIEW ON (
                ORCAMENTO_PROD.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND ORCAMENTO_PROD.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
            )
            JOIN DBA.CIDADES_IBGE AS CI ON (CI.IDCIDADE = ORCAMENTO.IDCIDADE)
            JOIN DBA.MARCA AS MARCA ON (MARCA.DESCRICAO = PRODUTOS_VIEW.FABRICANTE)
        WHERE ORCAMENTO.FLAGPRENOTAPAGA = 'T'
            AND --        ORCAMENTO_PROD.IDVENDEDOR IN (:RA_IDVENDEDOR)  AND
            DATE(ORCAMENTO.DTMOVIMENTO) >= current date -365
            AND --       ORCAMENTO_PROD.IDORCAMENTO IN (:RA_IDORCAMENTO) AND
            --        ORCAMENTO_PROD.IDEMPRESA IN (:RA_IDEMPRESA) AND
            NOT EXISTS (
                SELECT 1
                FROM DBA.CLIENTE_FORNECEDOR AS CF,
                    DBA.EMPRESA AS EMP
                WHERE CF.CNPJCPF = EMP.CNPJ
                    AND CF.IDCLIFOR = ORCAMENTO.IDCLIFOR
                    AND EMP.IDEMPRESA IN (
                        SELECT DISTINCT IDEMPRESAENTRADA
                        FROM DBA.CONFIG_TRANSF_NOTA
                    )
            )
        UNION ALL
        SELECT DISTINCT 'D' AS TIPO,
            ORCAMENTO_PROD.IDEMPRESA,
            EMPRESA.NOMEFANTASIA,
            ORCAMENTO.IDCLIFOR,
            CLIENTE_FORNECEDOR.NOME,
            CI.DESCRCIDADE,
            CI.UF,
            DATE(ESTOQUE_ANALITICO.DTMOVIMENTO) AS DATA,
            ORCAMENTO_PROD.IDORCAMENTO,
            ORCAMENTO_PROD.IDVENDEDOR,
            ORCAMENTO_PROD.IDPRODUTO,
            ORCAMENTO_PROD.IDSUBPRODUTO,
            PRODUTOS_VIEW.FABRICANTE AS MARCA,
            ORCAMENTO_PROD.NUMSEQUENCIA,
            PRODUTOS_VIEW.DESCRICAOPRODUTO AS DESCRICAOPRODUTO,
            0 AS VALOR_VENDA,
            0 AS VALFRETE_VENDA,
            COALESCE(NOTAS_DEVOLUCAO.VALTOTLIQUIDO, 0) AS VALOR_DEV,
            -- INICIO AJUSTE POR SERGIO JUNIOR [29/06/2020]
            CASE
                WHEN COALESCE(ESTOQUE_ANALITICO.VALFRETE, 0) = 0 THEN (
                    COALESCE(ORCAMENTO_PROD.VALFRETE, 0) / ORCAMENTO_PROD.QTDPRODUTO
                ) * ESTOQUE_ANALITICO.QTDPRODUTO
                ELSE COALESCE(ESTOQUE_ANALITICO.VALFRETE, 0)
            END AS VALFRETE_DEV,
            -- FIM AJUSTE POR SERGIO JUNIOR [29/06/2020]
            0 AS VALOR_CAN
        FROM DBA.ESTOQUE_ANALITICO AS ESTOQUE_ANALITICO
            JOIN DBA.NOTAS_DEVOLUCAO AS NOTAS_DEVOLUCAO ON (
                NOTAS_DEVOLUCAO.IDEMPRESA = ESTOQUE_ANALITICO.IDEMPRESA
                AND NOTAS_DEVOLUCAO.IDPLANILHA = ESTOQUE_ANALITICO.IDPLANILHA
                AND NOTAS_DEVOLUCAO.IDPRODUTO = ESTOQUE_ANALITICO.IDPRODUTO
                AND NOTAS_DEVOLUCAO.IDSUBPRODUTO = ESTOQUE_ANALITICO.IDSUBPRODUTO
                AND NOTAS_DEVOLUCAO.NUMSEQUENCIADEVOLUCAO = ESTOQUE_ANALITICO.NUMSEQUENCIA
            )
            JOIN DBA.DEVOLUCAO_LOGISTICA_MOVIMENTO AS DEVOLUCAO_LOGISTICA_MOVIMENTO ON (
                DEVOLUCAO_LOGISTICA_MOVIMENTO.IDEMPRESA = NOTAS_DEVOLUCAO.IDEMPRESA
                AND DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPLANILHA = NOTAS_DEVOLUCAO.IDPLANILHA
                AND DEVOLUCAO_LOGISTICA_MOVIMENTO.NUMSEQUENCIALANC = NOTAS_DEVOLUCAO.NUMSEQUENCIADEVOLUCAO
                AND DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPRODUTO = NOTAS_DEVOLUCAO.IDPRODUTO
                AND DEVOLUCAO_LOGISTICA_MOVIMENTO.IDSUBPRODUTO = NOTAS_DEVOLUCAO.IDSUBPRODUTO
                AND DEVOLUCAO_LOGISTICA_MOVIMENTO.FLAGGERARREENTREGA = 'F'
            )
            JOIN DBA.ORCAMENTO_PRE_NOTA AS ORCAMENTO_PRE_NOTA ON (
                ORCAMENTO_PRE_NOTA.IDEMPRESAPRENOTA = DEVOLUCAO_LOGISTICA_MOVIMENTO.IDEMPRESA
                AND ORCAMENTO_PRE_NOTA.IDPLANILHAPRENOTA = DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPLANILHADOCORI
            )
            JOIN DBA.ORCAMENTO_PROD_NOTA AS ORCAMENTO_PROD_NOTA ON (
                ORCAMENTO_PRE_NOTA.IDEMPRESAORCAMENTO = ORCAMENTO_PROD_NOTA.IDEMPRESAORCAMENTO
                AND ORCAMENTO_PRE_NOTA.IDORCAMENTO = ORCAMENTO_PROD_NOTA.IDORCAMENTO
                AND ORCAMENTO_PROD_NOTA.IDPRODUTO = DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPRODUTO
                AND ORCAMENTO_PROD_NOTA.IDSUBPRODUTO = DEVOLUCAO_LOGISTICA_MOVIMENTO.IDSUBPRODUTO
                AND ORCAMENTO_PROD_NOTA.NUMSEQUENCIA = DEVOLUCAO_LOGISTICA_MOVIMENTO.NUMSEQUENCIADOC
            )
            JOIN DBA.ORCAMENTO_PROD AS ORCAMENTO_PROD ON (
                ORCAMENTO_PROD.IDEMPRESA = ORCAMENTO_PROD_NOTA.IDEMPRESAORCAMENTO
                AND ORCAMENTO_PROD.IDORCAMENTO = ORCAMENTO_PROD_NOTA.IDORCAMENTO
                AND ORCAMENTO_PROD.IDPRODUTO = ORCAMENTO_PROD_NOTA.IDPRODUTO
                AND ORCAMENTO_PROD.IDSUBPRODUTO = ORCAMENTO_PROD_NOTA.IDSUBPRODUTO
                AND ORCAMENTO_PROD.NUMSEQUENCIA = ORCAMENTO_PROD_NOTA.NUMSEQUENCIA
            )
            JOIN DBA.PRODUTOS_VIEW AS PRODUTOS_VIEW ON (
                ORCAMENTO_PROD.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND ORCAMENTO_PROD.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
            )
            JOIN DBA.ORCAMENTO AS ORCAMENTO ON (
                ORCAMENTO.IDEMPRESA = ORCAMENTO_PROD.IDEMPRESA
                AND ORCAMENTO.IDORCAMENTO = ORCAMENTO_PROD.IDORCAMENTO
            )
            JOIN DBA.CLIENTE_FORNECEDOR AS CLIENTE_FORNECEDOR ON (ORCAMENTO.IDCLIFOR = CLIENTE_FORNECEDOR.IDCLIFOR)
            JOIN DBA.EMPRESA AS EMPRESA ON (EMPRESA.IDEMPRESA = ORCAMENTO.IDEMPRESA)
            JOIN DBA.CIDADES_IBGE AS CI ON (CI.IDCIDADE = ORCAMENTO.IDCIDADE)
            JOIN DBA.MARCA AS MARCA ON (MARCA.DESCRICAO = PRODUTOS_VIEW.FABRICANTE)
        WHERE DEVOLUCAO_LOGISTICA_MOVIMENTO.FLAGENTREGACANCELADA = 'F'
            AND ORCAMENTO.FLAGPRENOTAPAGA = 'T'
            AND --        ORCAMENTO_PROD.IDVENDEDOR IN (:RA_IDVENDEDOR)  AND
            ESTOQUE_ANALITICO.DTMOVIMENTO >= current date -365
            AND --       ORCAMENTO_PROD.IDORCAMENTO IN (:RA_IDORCAMENTO) AND
            --        ESTOQUE_ANALITICO.IDEMPRESA IN (:RA_IDEMPRESA) AND
            NOT EXISTS (
                SELECT 1
                FROM DBA.CLIENTE_FORNECEDOR AS CF,
                    DBA.EMPRESA AS EMP
                WHERE CF.CNPJCPF = EMP.CNPJ
                    AND CF.IDCLIFOR = ORCAMENTO.IDCLIFOR
                    AND EMP.IDEMPRESA IN (
                        SELECT DISTINCT IDEMPRESAENTRADA
                        FROM DBA.CONFIG_TRANSF_NOTA
                    )
            )
        UNION ALL
        SELECT DISTINCT 'C' AS TIPO,
            ORCAMENTO_PROD.IDEMPRESA,
            EMPRESA.NOMEFANTASIA,
            ORCAMENTO.IDCLIFOR,
            CLIENTE_FORNECEDOR.NOME,
            CI.DESCRCIDADE,
            CI.UF,
            DATE(DEVOLUCAO_LOGISTICA_MOVIMENTO.DTDEVOLUCAO) AS DATA,
            ORCAMENTO_PROD.IDORCAMENTO,
            ORCAMENTO_PROD.IDVENDEDOR,
            ORCAMENTO_PROD.IDPRODUTO,
            ORCAMENTO_PROD.IDSUBPRODUTO,
            PRODUTOS_VIEW.FABRICANTE AS MARCA,
            ORCAMENTO_PROD.NUMSEQUENCIA,
            PRODUTOS_VIEW.DESCRICAOPRODUTO AS DESCRICAOPRODUTO,
            0 AS VALOR_VENDA,
            0 AS VALFRETE_VENDA,
            0 AS VALOR_DEV,
            0 AS VALFRETE_DEV,
            CASE
                WHEN ROUND(
                    (
                        COALESCE(DEVOLUCAO_LOGISTICA_MOVIMENTO.QTDPRODUTO, 0) * (
                            COALESCE(ORCAMENTO_PROD.VALTOTLIQUIDO, 0) / COALESCE(ORCAMENTO_PROD.QTDPRODUTO, 0)
                        )
                    ),
                    2
                ) > 0 THEN ROUND(
                    (
                        (
                            COALESCE(DEVOLUCAO_LOGISTICA_MOVIMENTO.QTDPRODUTO, 0) * (
                                COALESCE(ORCAMENTO_PROD.VALTOTLIQUIDO, 0) / COALESCE(ORCAMENTO_PROD.QTDPRODUTO, 0)
                            )
                        ) - COALESCE(ORCAMENTO_PROD.VALFRETE, 0)
                    ),
                    2
                )
                ELSE ROUND(
                    (
                        COALESCE(DEVOLUCAO_LOGISTICA_MOVIMENTO.QTDPRODUTO, 0) * (
                            COALESCE(ORCAMENTO_PROD.VALTOTLIQUIDO, 0) / COALESCE(ORCAMENTO_PROD.QTDPRODUTO, 0)
                        )
                    ),
                    2
                )
            END AS VALOR_CAN
        FROM DBA.EMPRESA AS EMPRESA
            JOIN DBA.ORCAMENTO AS ORCAMENTO ON (EMPRESA.IDEMPRESA = ORCAMENTO.IDEMPRESA)
            JOIN DBA.CLIENTE_FORNECEDOR AS CLIENTE_FORNECEDOR ON (ORCAMENTO.IDCLIFOR = CLIENTE_FORNECEDOR.IDCLIFOR)
            JOIN DBA.ORCAMENTO_PROD AS ORCAMENTO_PROD ON (
                ORCAMENTO.IDEMPRESA = ORCAMENTO_PROD.IDEMPRESA
                AND ORCAMENTO.IDORCAMENTO = ORCAMENTO_PROD.IDORCAMENTO
            )
            JOIN DBA.PRODUTOS_VIEW AS PRODUTOS_VIEW ON (
                ORCAMENTO_PROD.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND ORCAMENTO_PROD.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
            )
            JOIN DBA.ORCAMENTO_PRE_NOTA AS ORCAMENTO_PRE_NOTA ON (
                ORCAMENTO_PROD.IDEMPRESA = ORCAMENTO_PRE_NOTA.IDEMPRESAORCAMENTO
                AND ORCAMENTO_PROD.IDORCAMENTO = ORCAMENTO_PRE_NOTA.IDORCAMENTO
            )
            JOIN DBA.DEVOLUCAO_LOGISTICA_MOVIMENTO AS DEVOLUCAO_LOGISTICA_MOVIMENTO ON (
                ORCAMENTO_PRE_NOTA.IDEMPRESAPRENOTA = DEVOLUCAO_LOGISTICA_MOVIMENTO.IDEMPRESA
                AND ORCAMENTO_PRE_NOTA.IDPLANILHAPRENOTA = DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPLANILHADOCORI
                AND ORCAMENTO_PROD.IDPRODUTO = DEVOLUCAO_LOGISTICA_MOVIMENTO.IDPRODUTO
                AND ORCAMENTO_PROD.IDSUBPRODUTO = DEVOLUCAO_LOGISTICA_MOVIMENTO.IDSUBPRODUTO
                AND ORCAMENTO_PROD.NUMSEQUENCIA = DEVOLUCAO_LOGISTICA_MOVIMENTO.NUMSEQUENCIADOC
            )
            JOIN DBA.CIDADES_IBGE AS CI ON (CI.IDCIDADE = ORCAMENTO.IDCIDADE)
            JOIN DBA.MARCA AS MARCA ON (MARCA.DESCRICAO = PRODUTOS_VIEW.FABRICANTE)
        WHERE DEVOLUCAO_LOGISTICA_MOVIMENTO.FLAGENTREGACANCELADA = 'T'
            AND --       ORCAMENTO_PROD.IDORCAMENTO IN (:RA_IDORCAMENTO) AND
            ORCAMENTO.FLAGPRENOTAPAGA = 'T'
            AND --        ORCAMENTO_PROD.IDVENDEDOR IN (:RA_IDVENDEDOR)  AND
            DATE(DEVOLUCAO_LOGISTICA_MOVIMENTO.DTDEVOLUCAO) >= current date -365
            AND --        ORCAMENTO_PROD.IDEMPRESA IN (:RA_IDEMPRESA) AND
            NOT EXISTS (
                SELECT 1
                FROM DBA.CLIENTE_FORNECEDOR AS CF,
                    DBA.EMPRESA AS EMP
                WHERE CF.CNPJCPF = EMP.CNPJ
                    AND CF.IDCLIFOR = ORCAMENTO.IDCLIFOR
                    AND EMP.IDEMPRESA IN (
                        SELECT DISTINCT IDEMPRESAENTRADA
                        FROM DBA.CONFIG_TRANSF_NOTA
                    )
            )
    ) AS TEMP
    LEFT JOIN DBA.MARGEM_CONTRIBUICAO AS MARGEM_CONTRIBUICAO ON (
        TEMP.IDEMPRESA = MARGEM_CONTRIBUICAO.IDEMPRESA
        AND TEMP.IDORCAMENTO = MARGEM_CONTRIBUICAO.IDDOCUMENTO
        AND TEMP.NUMSEQUENCIA = MARGEM_CONTRIBUICAO.NUMSEQUENCIA
        AND MARGEM_CONTRIBUICAO.TIPODOCUMENTO = 'P'
    )
    LEFT JOIN DBA.CLIENTE_FORNECEDOR AS VENDEDOR ON (TEMP.IDVENDEDOR = VENDEDOR.IDCLIFOR)
    LEFT JOIN DBA.DEPARTAMENTOS AS DEPARTAMENTOS ON (
        VENDEDOR.IDDEPARTAMENTO = DEPARTAMENTOS.IDDEPARTAMENTO
    )
    LEFT JOIN (
        SELECT CLUBE_INDICADOR_ORCAMENTO.IDEMPRESA,
            CLUBE_INDICADOR_ORCAMENTO.IDORCAMENTO,
            CLUBE_INDICADOR_ORCAMENTO.IDCLUBE,
            CLUBE_FIDELIZACAO.DESCRCLUBE,
            CLUBE_INDICADOR_ORCAMENTO.IDINDICADOR,
            INDICADOR.NOME AS NOMEINDICADOR,
            INDICADOR.CNPJCPF AS CNPJCPF_IND,
            INDICADOR.FONECELULAR AS FONECELULAR
        FROM DBA.CLUBE_INDICADOR_ORCAMENTO AS CLUBE_INDICADOR_ORCAMENTO
            JOIN DBA.CLUBE_FIDELIZACAO AS CLUBE_FIDELIZACAO ON (
                CLUBE_INDICADOR_ORCAMENTO.IDCLUBE = CLUBE_FIDELIZACAO.IDCLUBE
            )
            JOIN DBA.CLIENTE_FORNECEDOR AS INDICADOR ON (
                CLUBE_INDICADOR_ORCAMENTO.IDINDICADOR = INDICADOR.IDCLIFOR
            ) --   WHERE
            --        CLUBE_INDICADOR_ORCAMENTO.IDEMPRESA IN (:RA_IDEMPRESA) AND
            --       CLUBE_INDICADOR_ORCAMENTO.IDORCAMENTO IN (:RA_IDORCAMENTO)
            --        CLUBE_INDICADOR_ORCAMENTO.IDINDICADOR IN (:RA_IDINDICADOR)
    ) AS CLUBE ON (
        TEMP.IDEMPRESA = CLUBE.IDEMPRESA
        AND TEMP.IDORCAMENTO = CLUBE.IDORCAMENTO
    )
WHERE 1 = 1
    and VENDEDOR.IDCLIFOR in (':IDVENDEDOR')
    and CLUBE.IDINDICADOR IS NOT NULL
GROUP BY CLUBE.IDINDICADOR,
    CLUBE.NOMEINDICADOR,
    CLUBE.CNPJCPF_IND,
    CLUBE.FONECELULAR,
    VENDEDOR.IDCLIFOR,
    VENDEDOR.NOME
UNION ALL
SELECT CLUBE.IDINDICADOR,
    CLUBE.NOMEINDICADOR,
    CLUBE.CNPJCPF_IND,
    CAST(count(temp.idorcamento) AS VARCHAR(10)) as qtdvendas,
    CLUBE.FONECELULAR,
    VENDEDOR.IDCLIFOR AS IDVENDEDOR,
    VENDEDOR.NOME AS NOMEVENDEDOR,
    MAX(TEMP.DATA) AS ULTIMACOMPRA,
    CAST(
        DAYS(CURRENT DATE) - DAYS(MAX(TEMP.DATA)) AS VARCHAR(10)
    ) AS DIASSEMCOMPRA,
    (
        CASE
            WHEN (CURRENT DATE - MAX(TEMP.DATA)) BETWEEN 61 AND 90 THEN 'ATENÇÃO'
            WHEN (CURRENT DATE - MAX(TEMP.DATA)) > 91 THEN 'INATIVO'
            ELSE 'ATIVO'
        END
    ) AS STATUS,
    CAST(
        ROUND(SUM(COALESCE(TEMP.VALOR_VENDA, 0)), 2) AS VARCHAR(20)
    ) AS VALOR_VENDA_INDICADOR,
    CAST(
        ROUND(SUM(COALESCE(TEMP.VALFRETE_VENDA, 0)), 2) AS VARCHAR(20)
    ) AS VALFRETE_VENDA_INDICADOR,
    CAST(
        ROUND(
            SUM(COALESCE(TEMP.VALOR_DEV, 0)) - SUM(COALESCE(TEMP.VALFRETE_DEV, 0)),
            2
        ) AS VARCHAR(20)
    ) AS VALOR_DEV_INDICADOR,
    CAST(
        ROUND(SUM(COALESCE(TEMP.VALOR_CAN, 0)), 2) AS VARCHAR(20)
    ) AS VALOR_CAN_INDICADOR,
    CAST(
        ROUND(
            (
                (
                    SUM(COALESCE(TEMP.VALOR_VENDA, 0)) - SUM(COALESCE(TEMP.VALFRETE_VENDA, 0))
                ) - (
                    SUM(COALESCE(TEMP.VALOR_DEV, 0)) - SUM(COALESCE(TEMP.VALFRETE_DEV, 0))
                ) - (SUM(COALESCE(TEMP.VALOR_CAN, 0)))
            ),
            2
        ) AS VARCHAR(20)
    ) AS VALORLIQUIDOVENDAINDICADOR
FROM (
        SELECT 'VF' AS TIPO,
            ESTOQUE_ANALITICO.IDEMPRESA,
            EMPRESA.NOMEFANTASIA,
            NOTAS.IDCLIFOR,
            CLIENTE_FORNECEDOR.NOME,
            CI.DESCRCIDADE,
            CI.UF,
            DATE(ESTOQUE_ANALITICO.DTMOVIMENTO) AS DATA,
            NOTAS.IDPLANILHA AS IDORCAMENTO,
            ESTOQUE_ANALITICO.IDVENDEDOR,
            ESTOQUE_ANALITICO.IDPRODUTO,
            ESTOQUE_ANALITICO.IDSUBPRODUTO,
            PRODUTOS_VIEW.FABRICANTE AS MARCA,
            ESTOQUE_ANALITICO.NUMSEQUENCIA,
            PRODUTOS_VIEW.DESCRICAOPRODUTO AS DESCRICAOPRODUTO,
            COALESCE(ESTOQUE_ANALITICO.VALTOTLIQUIDO, 0) AS VALOR_VENDA,
            COALESCE(ESTOQUE_ANALITICO.VALFRETE, 0) AS VALFRETE_VENDA,
            0 AS VALOR_DEV,
            0 AS VALFRETE_DEV,
            0 AS VALOR_CAN
        FROM DBA.EMPRESA AS EMPRESA
            JOIN DBA.NOTAS AS NOTAS ON (EMPRESA.IDEMPRESA = NOTAS.IDEMPRESA)
            JOIN DBA.CLIENTE_FORNECEDOR AS CLIENTE_FORNECEDOR ON (NOTAS.IDCLIFOR = CLIENTE_FORNECEDOR.IDCLIFOR)
            JOIN DBA.NOTAS_ENTRADA_SAIDA AS NOTAS_ENTRADA_SAIDA ON (
                NOTAS.IDEMPRESA = NOTAS_ENTRADA_SAIDA.IDEMPRESA
                AND NOTAS.IDPLANILHA = NOTAS_ENTRADA_SAIDA.IDPLANILHA
            )
            JOIN DBA.ESTOQUE_ANALITICO AS ESTOQUE_ANALITICO ON (
                NOTAS.IDEMPRESA = ESTOQUE_ANALITICO.IDEMPRESA
                AND NOTAS.IDPLANILHA = ESTOQUE_ANALITICO.IDPLANILHA
            )
            JOIN DBA.PRODUTOS_VIEW AS PRODUTOS_VIEW ON (
                ESTOQUE_ANALITICO.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND ESTOQUE_ANALITICO.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
            )
            JOIN DBA.OPERACAO_INTERNA AS OPERACAO_INTERNA ON (
                ESTOQUE_ANALITICO.IDOPERACAO = OPERACAO_INTERNA.IDOPERACAO
            )
            JOIN DBA.CIDADES_IBGE AS CI ON (CI.IDCIDADE = NOTAS_ENTRADA_SAIDA.IDCIDADE)
            JOIN DBA.MARCA AS MARCA ON (MARCA.DESCRICAO = PRODUTOS_VIEW.FABRICANTE)
        WHERE OPERACAO_INTERNA.TIPOMOVIMENTO IN ('V')
            AND NOTAS_ENTRADA_SAIDA.TIPOCATEGORIA IN ('A')
            AND NOTAS_ENTRADA_SAIDA.TIPOITEMCATEGORIA IN ('A2')
            AND COALESCE(ESTOQUE_ANALITICO.NUMSEQUENCIAKIT, 0) <= 0
            AND NOTAS.FLAGNOTACANCEL = 'F'
            AND --        ESTOQUE_ANALITICO.IDVENDEDOR IN (:RA_IDVENDEDOR)  AND
            ESTOQUE_ANALITICO.DTMOVIMENTO >= current date -365
            AND --       NOTAS.NUMNOTA IN (:RA_IDORCAMENTO) AND
            --        ESTOQUE_ANALITICO.IDEMPRESA IN (:RA_IDEMPRESA) AND
            NOT EXISTS (
                SELECT 1
                FROM DBA.CLIENTE_FORNECEDOR AS CF,
                    DBA.EMPRESA AS EMP
                WHERE CF.CNPJCPF = EMP.CNPJ
                    AND CF.IDCLIFOR = NOTAS.IDCLIFOR
                    AND EMP.IDEMPRESA IN (
                        SELECT DISTINCT IDEMPRESAENTRADA
                        FROM DBA.CONFIG_TRANSF_NOTA
                    )
            )
        UNION ALL
        SELECT 'DVF' AS TIPO,
            NOTAS_DEVOLUCAO.IDEMPRESA,
            EMPRESA.NOMEFANTASIA,
            NOTAS.IDCLIFOR,
            CLIENTE_FORNECEDOR.NOME,
            CI.DESCRCIDADE,
            CI.UF,
            DATE(ESTOQUE_ANALITICO.DTMOVIMENTO) AS DATA,
            NOTAS_DEVOLUCAO.IDPLANILHADEVOLUCAO AS IDORCAMENTO,
            ESTOQUE_ANALITICO.IDVENDEDOR,
            ESTOQUE_ANALITICO.IDPRODUTO,
            ESTOQUE_ANALITICO.IDSUBPRODUTO,
            PRODUTOS_VIEW.FABRICANTE AS MARCA,
            NOTAS_DEVOLUCAO.NUMSEQUENCIADEVOLUCAO,
            PRODUTOS_VIEW.DESCRICAOPRODUTO AS DESCRICAOPRODUTO,
            0 AS VALOR_VENDA,
            0 AS VALFRETE_VENDA,
            COALESCE(ESTOQUE_ANALITICO.VALTOTLIQUIDO, 0) AS VALOR_DEV,
            COALESCE(ESTOQUE_ANALITICO.VALFRETE, 0) AS VALFRETE_DEV,
            0 AS VALOR_CAN
        FROM DBA.EMPRESA AS EMPRESA
            JOIN DBA.NOTAS AS NOTAS ON (EMPRESA.IDEMPRESA = NOTAS.IDEMPRESA)
            JOIN DBA.CLIENTE_FORNECEDOR AS CLIENTE_FORNECEDOR ON (NOTAS.IDCLIFOR = CLIENTE_FORNECEDOR.IDCLIFOR)
            JOIN DBA.NOTAS_ENTRADA_SAIDA AS NOTAS_ENTRADA_SAIDA ON (
                NOTAS.IDEMPRESA = NOTAS_ENTRADA_SAIDA.IDEMPRESA
                AND NOTAS.IDPLANILHA = NOTAS_ENTRADA_SAIDA.IDPLANILHA
            )
            JOIN DBA.ESTOQUE_ANALITICO AS ESTOQUE_ANALITICO ON (
                NOTAS.IDEMPRESA = ESTOQUE_ANALITICO.IDEMPRESA
                AND NOTAS.IDPLANILHA = ESTOQUE_ANALITICO.IDPLANILHA
            )
            JOIN DBA.NOTAS_DEVOLUCAO AS NOTAS_DEVOLUCAO ON (
                ESTOQUE_ANALITICO.IDEMPRESA = NOTAS_DEVOLUCAO.IDEMPRESA
                AND ESTOQUE_ANALITICO.IDPLANILHA = NOTAS_DEVOLUCAO.IDPLANILHA
                AND ESTOQUE_ANALITICO.NUMSEQUENCIA = NOTAS_DEVOLUCAO.NUMSEQUENCIADEVOLUCAO
                AND ESTOQUE_ANALITICO.IDPRODUTO = NOTAS_DEVOLUCAO.IDPRODUTO
                AND ESTOQUE_ANALITICO.IDSUBPRODUTO = NOTAS_DEVOLUCAO.IDSUBPRODUTO
            )
            JOIN DBA.PRODUTOS_VIEW AS PRODUTOS_VIEW ON (
                ESTOQUE_ANALITICO.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND ESTOQUE_ANALITICO.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
            )
            JOIN DBA.OPERACAO_INTERNA AS OPERACAO_INTERNA ON (
                ESTOQUE_ANALITICO.IDOPERACAO = OPERACAO_INTERNA.IDOPERACAO
            )
            JOIN DBA.CIDADES_IBGE AS CI ON (CI.IDCIDADE = NOTAS_ENTRADA_SAIDA.IDCIDADE)
            JOIN DBA.MARCA AS MARCA ON (MARCA.DESCRICAO = PRODUTOS_VIEW.FABRICANTE)
        WHERE OPERACAO_INTERNA.TIPOMOVIMENTO IN ('E')
            AND NOTAS_ENTRADA_SAIDA.TIPOCATEGORIA IN ('D')
            AND NOTAS_ENTRADA_SAIDA.TIPOITEMCATEGORIA IN ('D7')
            AND COALESCE(ESTOQUE_ANALITICO.NUMSEQUENCIAKIT, 0) <= 0
            AND NOTAS.FLAGNOTACANCEL = 'F'
            AND --        ESTOQUE_ANALITICO.IDVENDEDOR IN (:RA_IDVENDEDOR)  AND
            ESTOQUE_ANALITICO.DTMOVIMENTO >= current date -365
            AND --       NOTAS.NUMNOTA IN (:RA_IDORCAMENTO) AND
            --        ESTOQUE_ANALITICO.IDEMPRESA IN (:RA_IDEMPRESA) AND
            NOT EXISTS (
                SELECT 1
                FROM DBA.CLIENTE_FORNECEDOR AS CF,
                    DBA.EMPRESA AS EMP
                WHERE CF.CNPJCPF = EMP.CNPJ
                    AND CF.IDCLIFOR = NOTAS.IDCLIFOR
                    AND EMP.IDEMPRESA IN (
                        SELECT DISTINCT IDEMPRESAENTRADA
                        FROM DBA.CONFIG_TRANSF_NOTA
                    )
            )
    ) AS TEMP
    LEFT JOIN DBA.MARGEM_CONTRIBUICAO AS MARGEM_CONTRIBUICAO ON (
        TEMP.IDEMPRESA = MARGEM_CONTRIBUICAO.IDEMPRESA
        AND TEMP.IDORCAMENTO = MARGEM_CONTRIBUICAO.IDDOCUMENTO
        AND TEMP.NUMSEQUENCIA = MARGEM_CONTRIBUICAO.NUMSEQUENCIA
        AND MARGEM_CONTRIBUICAO.TIPODOCUMENTO = 'N'
    )
    LEFT JOIN DBA.CLIENTE_FORNECEDOR AS VENDEDOR ON (TEMP.IDVENDEDOR = VENDEDOR.IDCLIFOR)
    LEFT JOIN DBA.DEPARTAMENTOS AS DEPARTAMENTOS ON (
        VENDEDOR.IDDEPARTAMENTO = DEPARTAMENTOS.IDDEPARTAMENTO
    )
    LEFT JOIN (
        SELECT CLUBE_INDICADOR_ORCAMENTO.IDEMPRESA,
            CLUBE_INDICADOR_ORCAMENTO.IDORCAMENTO,
            CLUBE_INDICADOR_ORCAMENTO.IDCLUBE,
            CLUBE_FIDELIZACAO.DESCRCLUBE,
            CLUBE_INDICADOR_ORCAMENTO.IDINDICADOR,
            INDICADOR.NOME AS NOMEINDICADOR,
            INDICADOR.CNPJCPF AS CNPJCPF_IND,
            INDICADOR.FONECELULAR AS FONECELULAR
        FROM DBA.CLUBE_INDICADOR_ORCAMENTO AS CLUBE_INDICADOR_ORCAMENTO
            JOIN DBA.CLUBE_FIDELIZACAO AS CLUBE_FIDELIZACAO ON (
                CLUBE_INDICADOR_ORCAMENTO.IDCLUBE = CLUBE_FIDELIZACAO.IDCLUBE
            )
            JOIN DBA.CLIENTE_FORNECEDOR AS INDICADOR ON (
                CLUBE_INDICADOR_ORCAMENTO.IDINDICADOR = INDICADOR.IDCLIFOR
            ) --   WHERE
            --        CLUBE_INDICADOR_ORCAMENTO.IDEMPRESA IN (:RA_IDEMPRESA) AND
            --       CLUBE_INDICADOR_ORCAMENTO.IDORCAMENTO IN (:RA_IDORCAMENTO)
            --        CLUBE_INDICADOR_ORCAMENTO.IDINDICADOR IN (:RA_IDINDICADOR)
    ) AS CLUBE ON (
        TEMP.IDEMPRESA = CLUBE.IDEMPRESA
        AND TEMP.IDORCAMENTO = CLUBE.IDORCAMENTO
    )
WHERE 1 = 1
    and VENDEDOR.IDCLIFOR in (':IDVENDEDOR')
    and CLUBE.IDINDICADOR IS NOT NULL
GROUP BY CLUBE.IDINDICADOR,
    CLUBE.NOMEINDICADOR,
    CLUBE.CNPJCPF_IND,
    CLUBE.FONECELULAR,
    VENDEDOR.IDCLIFOR,
    VENDEDOR.NOME