select IDEMPRESA,
    DATA,
    IDVENDEDOR,
    IDPRODUTO,
    IDSUBPRODUTO,
    MARCA,
    DESCRPRODUTO,
    NUMSEQUENCIA,
    QTDPRODUTO,
    VALORVENDALIQ,
    VALORFRETEVENDA
from VENDAS_BI_ELEVATO
WHERE IDORCAMENTO = ':IDPEDIDO'