SELECT IDSUBPRODUTO,
    DESCRCOMPRODUTO,
    PERCOMAVISTA,
    VALPRECOVAREJO,
    VALPROMVAREJO,
    DESCRGRUPO,
    DESCRSUBGRUPO,
    DESCRSECAO,
    EMBALAGEMSAIDA,
    DATAFINALPROMOCAO,
    CAST(MULTIPLOVENDA AS VARCHAR(20)) AS MULTIPLOVENDA,
    CAST(SUM(ESTOQUEGRAVATAI) AS VARCHAR(20)) AS ESTOQUEGRAVATAI,
    CAST(SUM(ESTOQUESEVERO) AS VARCHAR(20)) AS ESTOQUESEVERO
FROM (
        SELECT PRODUTOS_VIEW.IDSUBPRODUTO,
            CAST(PRODUTOS_VIEW.VALMULTIVENDAS AS VARCHAR(20)) AS VALMULTIVENDAS,
            cAST(PRODUTOS_VIEW.PERCOMAVISTA AS VARCHAR(20)) AS PERCOMAVISTA,
            PRODUTOS_VIEW.NCM,
            CAST(PRODUTOS_VIEW.PESOBRUTO AS VARCHAR(20)) AS PESOBRUTO,
            EMBALAGEMSAIDA,
            CAST(LARGURA AS VARCHAR(20)) AS LARGURA,
            CAST(ALTURA AS VARCHAR(20)) AS ALTURA,
            CAST(COMPRIMENTO AS VARCHAR(20)) AS COMPRIMENTO,
            PRODUTOS_VIEW.DESCRCOMPRODUTO,
            PRODUTOS_VIEW.FABRICANTE,
            PRODUTOS_VIEW.FLAGINATIVOCOMPRA,
            DIVISAO.IDDIVISAO,
            DIVISAO.DESCRDIVISAO,
            SECAO.IDSECAO,
            SECAO.DESCRSECAO,
            GRUPO.IDGRUPO,
            GRUPO.DESCRGRUPO,
            SUBGRUPO.IDSUBGRUPO,
            SUBGRUPO.DESCRSUBGRUPO,
            PRODUTO_FORNECEDOR.IDCLIFOR,
            CLIENTE_FORNECEDOR.IDGRUPOECONOMICO,
            GRUPO_ECONOMICO.DESCRGRUPOECONOMICO,
            CAST(ROUND(PPP.VALPRECOVAREJO, 2) AS VARCHAR(20)) AS VALPRECOVAREJO,
            CAST(
                ROUND(
                    (
                        CASE
                            WHEN PPP.DTFIMPROMOCAOVAR >= CURRENT DATE THEN PPP.VALPROMVAREJO
                            ELSE 0
                        END
                    ),
                    2
                ) AS VARCHAR(20)
            ) AS VALPROMVAREJO,
            PRODUTOS_VIEW.IDCODBARPROD,
            PRODUTOS_VIEW.REFERENCIA,
            PPP.DTFIMPROMOCAOVAR,
            0 AS ESTOQUEGRAVATAI,
            PSV1.QTDDISPONIVEL AS ESTOQUESEVERO,
            PPP.DTFIMPROMOCAOVAR AS DATAFINALPROMOCAO,
            PRODUTO_GRADE.VALMULTIVENDAS AS MULTIPLOVENDA
        FROM DBA.PRODUTOS_VIEW AS PRODUTOS_VIEW
            LEFT JOIN DBA.PRODUTOS_SALDOS_VIEW AS PSV1 ON PRODUTOS_VIEW.IDPRODUTO = PSV1.IDPRODUTO
            AND PRODUTOS_VIEW.IDSUBPRODUTO = PSV1.IDSUBPRODUTO
            AND PSV1.IDEMPRESA = 13
            AND PSV1.IDLOCALESTOQUE = 6
            AND PSV1.QTDDISPONIVEL > 0
            LEFT JOIN DBA.DIVISAO AS DIVISAO ON (DIVISAO.IDDIVISAO = PRODUTOS_VIEW.IDDIVISAO)
            LEFT JOIN DBA.SECAO AS SECAO ON (SECAO.IDSECAO = PRODUTOS_VIEW.IDSECAO)
            LEFT JOIN DBA.GRUPO AS GRUPO ON (GRUPO.IDGRUPO = PRODUTOS_VIEW.IDGRUPO)
            LEFT JOIN DBA.SUBGRUPO AS SUBGRUPO ON (SUBGRUPO.IDSUBGRUPO = PRODUTOS_VIEW.IDSUBGRUPO)
            LEFT JOIN DBA.PRODUTO_FORNECEDOR AS PRODUTO_FORNECEDOR ON (
                PRODUTO_FORNECEDOR.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
                AND PRODUTO_FORNECEDOR.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND PRODUTO_FORNECEDOR.FLAGFORNECEDORPADRAO = 'T'
            )
            LEFT JOIN DBA.CLIENTE_FORNECEDOR AS CLIENTE_FORNECEDOR ON (
                CLIENTE_FORNECEDOR.IDCLIFOR = PRODUTO_FORNECEDOR.IDCLIFOR
            )
            LEFT JOIN DBA.GRUPO_ECONOMICO AS GRUPO_ECONOMICO ON (
                GRUPO_ECONOMICO.IDGRUPOECONOMICO = CLIENTE_FORNECEDOR.IDGRUPOECONOMICO
            )
            LEFT JOIN DBA.POLITICA_PRECO_PRODUTO AS PPP ON (
                PPP.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND PPP.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
                AND PPP.IDEMPRESA = ':IDEMPRESA'
            )
            LEFT JOIN DBA.PRODUTO_GRADE AS PRODUTO_GRADE ON (
                PRODUTO_GRADE.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND PRODUTO_GRADE.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
            )
            LEFT JOIN DBA.PRODUTO_FAIXA_DETALHE AS PRODUTO_FAIXA_DETALHE ON (
                PRODUTO_GRADE.IDTAMANHO = PRODUTO_FAIXA_DETALHE.IDTAMANHO
            )
            LEFT JOIN DBA.PRODUTO_FAIXA AS PRODUTO_FAIXA ON (
                PRODUTO_FAIXA_DETALHE.IDFAIXA = PRODUTO_FAIXA.IDFAIXA
            )
        where (
                PRODUTOS_VIEW.DESCRCOMPRODUTO LIKE '%:FABRICANTE%'
            )
            AND (
                PSV1.QTDDISPONIVEL >= :QTDMAIOR
                OR :QTDMAIOR = -99999
            )
            AND PRODUTOS_VIEW.FLAGINATIVO = 'F'
        UNION ALL
        SELECT PRODUTOS_VIEW.IDSUBPRODUTO,
            CAST(PRODUTOS_VIEW.VALMULTIVENDAS AS VARCHAR(20)) AS VALMULTIVENDAS,
            cAST(PRODUTOS_VIEW.PERCOMAVISTA AS VARCHAR(20)) AS PERCOMAVISTA,
            PRODUTOS_VIEW.NCM,
            CAST(PRODUTOS_VIEW.PESOBRUTO AS VARCHAR(20)) AS PESOBRUTO,
            EMBALAGEMSAIDA,
            CAST(LARGURA AS VARCHAR(20)) AS LARGURA,
            CAST(ALTURA AS VARCHAR(20)) AS ALTURA,
            CAST(COMPRIMENTO AS VARCHAR(20)) AS COMPRIMENTO,
            PRODUTOS_VIEW.DESCRCOMPRODUTO,
            PRODUTOS_VIEW.FABRICANTE,
            PRODUTOS_VIEW.FLAGINATIVOCOMPRA,
            DIVISAO.IDDIVISAO,
            DIVISAO.DESCRDIVISAO,
            SECAO.IDSECAO,
            SECAO.DESCRSECAO,
            GRUPO.IDGRUPO,
            GRUPO.DESCRGRUPO,
            SUBGRUPO.IDSUBGRUPO,
            SUBGRUPO.DESCRSUBGRUPO,
            PRODUTO_FORNECEDOR.IDCLIFOR,
            CLIENTE_FORNECEDOR.IDGRUPOECONOMICO,
            GRUPO_ECONOMICO.DESCRGRUPOECONOMICO,
            CAST(ROUND(PPP.VALPRECOVAREJO, 2) AS VARCHAR(20)) AS VALPRECOVAREJO,
            CAST(
                ROUND(
                    (
                        CASE
                            WHEN PPP.DTFIMPROMOCAOVAR >= CURRENT DATE THEN PPP.VALPROMVAREJO
                            ELSE 0
                        END
                    ),
                    2
                ) AS VARCHAR(20)
            ) AS VALPROMVAREJO,
            PRODUTOS_VIEW.IDCODBARPROD,
            PRODUTOS_VIEW.REFERENCIA,
            PPP.DTFIMPROMOCAOVAR,
            PSV2.QTDDISPONIVEL AS ESTOQUEGRAVATAI,
            0 AS ESTOQUESEVERO,
            PPP.DTFIMPROMOCAOVAR AS DATAFINALPROMOCAO,
            PRODUTO_GRADE.VALMULTIVENDAS AS MULTIPLOVENDA
        FROM DBA.PRODUTOS_VIEW AS PRODUTOS_VIEW
            LEFT JOIN DBA.PRODUTOS_SALDOS_VIEW AS PSV2 ON PRODUTOS_VIEW.IDPRODUTO = PSV2.IDPRODUTO
            AND PRODUTOS_VIEW.IDSUBPRODUTO = PSV2.IDSUBPRODUTO
            AND PSV2.IDEMPRESA = 26
            AND PSV2.IDLOCALESTOQUE = 124
            AND PSV2.QTDDISPONIVEL > 0
            LEFT JOIN DBA.DIVISAO AS DIVISAO ON (DIVISAO.IDDIVISAO = PRODUTOS_VIEW.IDDIVISAO)
            LEFT JOIN DBA.SECAO AS SECAO ON (SECAO.IDSECAO = PRODUTOS_VIEW.IDSECAO)
            LEFT JOIN DBA.GRUPO AS GRUPO ON (GRUPO.IDGRUPO = PRODUTOS_VIEW.IDGRUPO)
            LEFT JOIN DBA.SUBGRUPO AS SUBGRUPO ON (SUBGRUPO.IDSUBGRUPO = PRODUTOS_VIEW.IDSUBGRUPO)
            LEFT JOIN DBA.PRODUTO_FORNECEDOR AS PRODUTO_FORNECEDOR ON (
                PRODUTO_FORNECEDOR.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
                AND PRODUTO_FORNECEDOR.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND PRODUTO_FORNECEDOR.FLAGFORNECEDORPADRAO = 'T'
            )
            LEFT JOIN DBA.CLIENTE_FORNECEDOR AS CLIENTE_FORNECEDOR ON (
                CLIENTE_FORNECEDOR.IDCLIFOR = PRODUTO_FORNECEDOR.IDCLIFOR
            )
            LEFT JOIN DBA.GRUPO_ECONOMICO AS GRUPO_ECONOMICO ON (
                GRUPO_ECONOMICO.IDGRUPOECONOMICO = CLIENTE_FORNECEDOR.IDGRUPOECONOMICO
            )
            LEFT JOIN DBA.POLITICA_PRECO_PRODUTO AS PPP ON (
                PPP.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND PPP.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
                AND PPP.IDEMPRESA = ':IDEMPRESA'
            )
            LEFT JOIN DBA.PRODUTO_GRADE AS PRODUTO_GRADE ON (
                PRODUTO_GRADE.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO
                AND PRODUTO_GRADE.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO
            )
        where (
                PRODUTOS_VIEW.DESCRCOMPRODUTO LIKE '%:FABRICANTE%'
            )
            and (
                PSV2.QTDDISPONIVEL >= :QTDMAIOR
                OR :QTDMAIOR = -99999
            )
            AND PRODUTOS_VIEW.FLAGINATIVO = 'F'
    ) AS RESUMO
GROUP BY IDSUBPRODUTO,
    DESCRCOMPRODUTO,
    PERCOMAVISTA,
    VALPRECOVAREJO,
    VALPROMVAREJO,
    DESCRGRUPO,
    DESCRSUBGRUPO,
    DESCRSECAO,
    DATAFINALPROMOCAO,
    MULTIPLOVENDA,
    EMBALAGEMSAIDA